INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('AED', 'DUI');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('AOA', 'LUA');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('BBD', 'BRI');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('BIF', 'BUJ');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('BSD', 'NAS');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('BWP', 'GAB');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('CAD', 'TOR');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('CDF', 'KSH');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('CHF', 'ZUR');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('CNH', 'BEJ');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('CVE', 'PRI');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('DJF', 'DJI');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('DZD', 'ARG');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('EGP', 'CAI');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('ERN', 'ASM');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('ETB', 'ADD');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('EUR', 'TARGET');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('GBP', 'LON');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('GHS', 'ACC');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('GMD', 'BNJ');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('GNF', 'CON');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('JPY', 'TOK');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('KES', 'NAI');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('KMF', 'MRN');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('LRD', 'MOR');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('LSL', 'MAS');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('LYD', 'TRI');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('MAD', 'RAB');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('MGA', 'ANT');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('MRU', 'NOU');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('MUR', 'PLS');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('MWK', 'LIL');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('MZN', 'MAP');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('NAD', 'WIN');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('NGN', 'LAG');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('RWF', 'KIG');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('SAR', 'RIY');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('SCR', 'VIC');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('SDG', 'KHA');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('SLL', 'FRE');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('SOS', 'MOG');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('SSP', 'JUB');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('STN', 'SAO');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('SZL', 'MBA');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('TND', 'TUN');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('TZS', 'DAR');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('UGX', 'KAM');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('USD', 'NYC');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('XAF', 'BIS');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('XAG', 'LON');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('XAU', 'LON');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('XOF', 'YAM');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('XPD', 'LON');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('XPT', 'LON');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('ZAR', 'JOH');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('ZIG', 'HAR');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('ZMW', 'LUS');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('ZWD', 'HAR');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('ZWG', 'HAR');
INSERT INTO CUSTOM.CURR_HOL_MAPPING
(CURRENY, HOLIDAY_CALENDAR)
VALUES('ZWL', 'HAR');