INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('12 MONTHS LIBOR RATE', 'Floating', '12MLB', 'USD', 'LIBOR', 'LIBOR01', '1Y');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('12 MONTH TERM SOFR', 'Floating', '12MTS', 'USD', 'TermSOFR', 'FRBNY', '1Y');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('NCCR LOAN NCCR LOAN FOR CIF: 6000010 CRNCY: USD', 'Floating', 'CA008', 'USD', 'SOFR', 'FRBNY', '1D');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('1 MONTH TERM SOFR', 'Floating', '01MTS', 'USD', 'TermSOFR', 'FRBNY', '1M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('6 MONTH TERM SOFR', 'Floating', '06MTS', 'USD', 'TermSOFR', 'FRBNY', '6M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('4 MONTHS LIBOR RATE - INTERPOLATED', 'Floating', '4MLBR', 'USD', 'LIBOR', 'LIBOR01', '6M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('6 MONTHS LIBOR RATE', 'Floating', '6MLBR', 'USD', 'LIBOR', 'LIBOR01', '6M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('3 MONTHS LIBOR RATE', 'Floating', '3MLBR', 'USD', 'LIBOR', 'LIBOR01', '3M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('NCCR LOAN FOR CIF: 3000551 CRNCY: USD', 'Floating', 'CA023', 'USD', 'SOFR', 'FRBNY', '1D');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('NCCR LOAN NCCR LOAN FOR CIF: 2000736 CRNCY: USD', 'Floating', 'CA004', 'USD', 'SOFR', 'FRBNY', '1D');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('NCCR LOAN FOR CIF: 2000048 CRNCY: USD', 'Floating', 'CA012', 'USD', 'SOFR', 'FRBNY', '1D');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('12 MONTHS EURIBOR', 'Floating', '12MUR', 'EUR', 'EURIBOR', 'EURIBOR01', '1Y');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('ZERO INTEREST', 'Fixed', 'CLZER', 'EUR', 'N.A', 'N.A', 'N.A');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('3 MONTH TERM SOFR', 'Floating', '03MTS', 'USD', 'TermSOFR', 'FRBNY', '3M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('COST OF FUND', 'Floating', 'COF01', 'USD', '-', '-', '-');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('3 MONTHS EURIBOR', 'Floating', '3MEUR', 'EUR', 'EURIBOR', 'EURIBOR01', '3M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('6 MONTHS EURIBOR', 'Floating', '6MEUR', 'EUR', 'EURIBOR', 'EURIBOR01', '6M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('5 MONTHS LIBOR RATE - INTERPOLATED', 'Floating', '5MLBR', 'USD', 'LIBOR', 'LIBOR01', '6M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('1 MONTH LIBOR RATE', 'Floating', '1MLBR', 'USD', 'LIBOR', 'LIBOR01', '1M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('ZERO INTEREST', 'Fixed', 'CLZER', 'USD', 'N.A', 'N.A', 'N.A');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('1 MONTH EURIBOR', 'Floating', '1MEUR', 'EUR', 'EURIBOR', 'EURIBOR01', '1M');
INSERT INTO CUSTOM.RATEINDEX_MAPPING
(INT_DESC, REPRICING_PLAN, BASE_RATE, CURRENCY, RATEINDEX, RATEINDEXSOURCE, TENOR)
VALUES('NCCR LOAN FOR CIF: 2000537 CRNCY: USD', 'Floating', 'CA018', 'USD', 'SOFR', 'FRBNY', '1D');